name: Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_app_name: 'medcab-rrc'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          procfile: 'web: node ./dist/index.js'
          buildpack: 'https://github.com/heroku/heroku-buildpack-nodejs.git'
        env:
          HD_IN_PROD: true
          HD_JWT_SECRET: ${{secrets.JWT_SECRET}}
          HD_MONGODB_DBNAME: ${{secrets.MONGODB_DBNAME}}
          HD_MONGODB_CONNECTION_STRING: ${{secrets.MONGODB_CONNECTION_STRING}}
          